### ISSUE TITLE
Support `host` option to serve app on local network

### ISSUE THREAD

**Issue by francoischalifour** [algolia/frontman#35]
## Description

Support custom hosts (via a `host` option) to serve the website on the local network (e.g., `0.0.0.0`).

## Motivation

Having a host option makes it easy to test your website on your local devices (mobiles, tablets, laptops, desktops, etc.). This enables good DX and empowers people to try their websites on different real devices connected to the same local network.

Most development server services offer this feature and I was frustrated not being able to try the website I'm working on on a real touch device.

## Solution

- Introduce a `host` string option that defaults to `localhost`
- Document that `0.0.0.0` can be set to open the website on your devices connected to the local network

## Additional context

- [Webpack Dev Server `host` option](https://webpack.js.org/configuration/dev-server/#devserverhost)
- [Parcel `host` option](https://en.parceljs.org/cli.html#host)

**Comment by DevinCodes** [comment]
Fixed in https://github.com/algolia/frontman/pull/36. This will be available when we release v0.0.5
