### ISSUE TITLE
QUESTION: Do you support Ruby 3? The gem's current pessimistic constraint is ambiguous...

### ISSUE THREAD

**Issue by thewoolleyman** [algolia/frontman#46]
Do you support Ruby 3?

The [current readme says 2.3 and up](https://github.com/algolia/frontman#installing-frontman), and the [rubygems page](https://rubygems.org/gems/frontman-ssg) says the constraint is: `~> 2, >= 2.3.0`.

But, it's unclear if you meant this to include Ruby 3 or not.

Note what whe [RubyGems docs say this](https://guides.rubygems.org/patterns/#declaring-dependencies):

> It’s also important to know that if you specify a major version only, like this:
> 
> ```ruby
> # gemspec
> spec.add_runtime_dependency 'library', '~> 2'
> ```
>
> It will only use the latest version from the 2.x series – so 2.3.0 – and not 3.0.0. This behaviour may surprise some people, but automatically allowing any major version past version 2 is more surprising behaviour.

It definitely surprised me, and I don't agree with it, but that's the way it is.

In any case, I would recommend:

1. If you do NOT support Ruby 3, change this constraint to `~> 2.3`, which I believe will accomplish what you want in this case.  Or...
2. If you DO support Ruby 3, change this constraint to `~> 3.0, >= 2.3.0`, which I believe will be correct, and avoid the ambiguity of a pessimistic constraint with only the major version specified (and it behaves identically to specifying major.minor anyway, per the above docs).

Thanks!

**Comment by DevinCodes** [comment]
Hey @thewoolleyman , thanks for reaching out!

I haven't tested Frontman with Ruby 3 for now, I'll take some time this week to test it and update the constraint as needed 😄

**Comment by thewoolleyman** [comment]
Thanks for doing this! 🥇

**Comment by DevinCodes** [comment]
Sure thing! It's not released yet as sorbet is breaking some things (see #49), but I plan on fixing that and releasing before the end of next week.
